name: Muhamamd Faisal

on:
  push:
    branches: [ master ]
 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install NodeJS
      uses: actions/setup-node@v-2-beta
      with: 
        node-version: 12
    
    - name: Install Surge
      run: npm install -g surge
    
    - name: Delopyment 
      run: surge ./ http://mfaisalpk.surge.sh/ --token ${{secrets.SURGE}}
      
      
      
